#!/bin/bash

# Installs Boombox (themes, vimrc, etc)
# for Vim on Linux (should run on Mac OSX
# also? No testing done however)
#
# Ensure this file is run when git repo
# is first added

echo "Any existing instances of ~/.vim and ~/.vimrc will be overwritten."
while true; do
    read -p "Would you like to proceed (y/n)?" check
    case $check in
        [Yy]* )
            # Remove existing ~/.vim and ~/.vimrc instances
            # Set up symbolic link to repo vimrc file
            rm -r -f ~/.vim
            mv ~/.boombox ~/.vim
            ln -f -s ~/.vim/.vimrc ~/vimrc
            echo "Vim setup complete."
            break;;
        [Nn]* )
            # Abort program
            echo "Exiting."
            exit;;
        * )
            # Check for invalid characters
            echo "Please answer only y or n."
    esac
done
